"""
Django settings for GatewayAPI project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
load_dotenv()
from decouple import config

KAFKA_BROKERS = "kafka:9092"
KAFKA_TOPIC = ""
SERVICE_NAME = "hi-ecom-product-api"
SALEOR_TOKEN = os.getenv("SALEOR_TOKEN","")
IS_DEV=os.getenv("IS_DEV","1")
USE_PRODUCTION = os.getenv("USE_PRODUCTION",None)
SALEOR_URL = "https://hifpt-api-stag.fpt.vn/hi-ecom-saleor-api/graphql"
if USE_PRODUCTION == "1":
    SALEOR_URL = ""
elif IS_DEV == "1":
    SALEOR_URL = "http://127.0.0.1:8000/graphql/"
    # SALEOR_URL = "https://hifpt-api-stag.fpt.vn/hi-ecom-saleor-api/graphql"

print("SALEOR_URL",SALEOR_URL)
print("SALEOR_TOKEN",SALEOR_TOKEN)

if USE_PRODUCTION == "1":
    LIST_BROKERS= ["isc-kafka01:9092", "isc-kafka02:9092", "isc-kafka03:9092"]
    HI_ECOM_TOPIC = "hifpt-hi-ecom-logs"
else:
    LIST_BROKERS= ["isc-kafka01:9092", "isc-kafka02:9092", "isc-kafka03:9092"]
    HI_ECOM_TOPIC = "stag-hifpt-hi-ecom-logs"

REDIS_CACHE_HOST = os.getenv("REDIS_CACHE_HOST","localhost")
REDIS_CACHE_PORT = os.getenv("REDIS_CACHE_PORT",1234)
REDIS_CACHE_PASSWORD = os.getenv("REDIS_CACHE_PASSWORD","password")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv("SECRET_KEY","")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hi_ecom_product_api',
    'graphene_django',
    'rest_framework'
]

GRAPHENE = {
    "SCHEMA": "hi_ecom_product_api.graphql.schema.schema"
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'src.configs.logging.middleware.LogKafkaMiddleware',
    # 'src.configs.logging.middleware.RequestIdMiddleware',
]

ROOT_URLCONF = 'hi_ecom_product_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hi_ecom_product_api.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
